// services/exchange/frontend/src/App.vue
<script setup>
import { ref, computed, onMounted } from 'vue';
import { 
  ArrowUpRight, 
  ArrowDownRight, 
  RefreshCcw, 
  Wallet, 
  TrendingUp,
  X
} from 'lucide-vue-next';

// --- CONFIGURATION ---
const API_BASE = "/api/exchange-service";
const USER_API_BASE = "/api/user-service";

// --- STATE ---
const storedUserId = localStorage.getItem('userId');
const currentUser = ref(storedUserId ? { id: storedUserId, name: '' } : null);

const balance = ref({ eur: 0, tokens: 0 });
const orders = ref([]);
const loading = ref(false);
const message = ref({ text: "", type: "" });
const userNames = ref({}); 

// Default to 'buy' mode
const tradeMode = ref('buy'); // 'buy' or 'sell' UI toggle

const newOrder = ref({
    type: "buy", 
    amount_token: null,
    amount_cash: null
});

// --- COMPUTED ---
const isValidOrder = computed(() => {
    return newOrder.value.amount_token > 0 && newOrder.value.amount_cash > 0;
});

const isLoggedIn = computed(() => !!currentUser.value);

// --- API CLIENT ---
const api = {
    async request(endpoint, options = {}) {
        if (!isLoggedIn.value) throw new Error("Authentication missing");
        const headers = { 'X-User-ID': currentUser.value.id, ...options.headers };
        const res = await fetch(`${API_BASE}${endpoint}`, { ...options, headers });
        
        let data;
        try { data = await res.json(); } 
        catch (e) { data = { error: await res.text() || res.statusText }; }

        if (!res.ok) throw new Error(data.error || 'Unknown Error');
        return data;
    },
    get(endpoint) { return this.request(endpoint); },
    post(endpoint, body) {
        return this.request(endpoint, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(body)
        });
    },
    delete(endpoint) { return this.request(endpoint, { method: 'DELETE' }); }
};

// --- LOGIC ---
const fetchUserName = async (userId) => {
    if (userNames.value[userId]) return;
    if (userId === currentUser.value.id && currentUser.value.name) {
        userNames.value[userId] = currentUser.value.name;
        return;
    }
    try {
        const res = await fetch(`${USER_API_BASE}/users/${userId}`);
        if (res.ok) {
            const data = await res.json();
            userNames.value[userId] = data.vorname;
        } else { userNames.value[userId] = "Unknown"; }
    } catch (e) { userNames.value[userId] = "Unknown"; }
};

const fetchMyName = async () => {
    if (!currentUser.value?.id) return;
    try {
        const res = await fetch(`${USER_API_BASE}/users/${currentUser.value.id}`);
        if (res.ok) {
            const data = await res.json();
            currentUser.value.name = data.vorname;
            userNames.value[currentUser.value.id] = data.vorname; 
        }
    } catch (e) { console.error(e); }
};

const fetchData = async () => {
    if (!isLoggedIn.value) return;
    loading.value = true;
    try {
        const [bal, ord] = await Promise.all([
            api.get('/balance'),
            api.get('/orders')
        ]);
        balance.value = bal;
        orders.value = ord;
        ord.forEach(order => fetchUserName(order.user_id));
    } catch (e) {
        showMessage("Connection Error", "error");
    } finally {
        loading.value = false;
    }
};

const createOrder = async () => {
    loading.value = true;
    // Set type based on current UI tab
    newOrder.value.type = tradeMode.value;
    
    try {
        await api.post('/orders', { ...newOrder.value });
        showMessage("Order Placed", "success");
        newOrder.value.amount_token = null;
        newOrder.value.amount_cash = null;
        await fetchData();
    } catch (e) {
        showMessage(e.message, "error");
    } finally {
        loading.value = false;
    }
};

const deleteOrder = async (orderId) => {
    try {
        await api.delete(`/orders/${orderId}`);
        await fetchData();
    } catch (e) { showMessage(e.message, "error"); }
};

const acceptOrder = async (order) => {
    try {
        await api.post(`/orders/${order.order_id}/accept`, {});
        showMessage("Transaction Successful", "success");
        await fetchData();
    } catch (e) { showMessage(e.message, "error"); }
};

// --- HELPER ---
const isMyOrder = (order) => order.user_id === currentUser.value?.id;
const formatCurrency = (val) => new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(val);
const formatCO2 = (val) => new Intl.NumberFormat('de-DE', { minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(val) + " g CO2";

const showMessage = (text, type) => {
    message.value = { text, type };
    setTimeout(() => message.value = { text: "", type: "" }, 3000);
};

onMounted(() => {
    if (isLoggedIn.value) {
        fetchMyName();
        fetchData();
        setInterval(fetchData, 4000); 
    }
});
</script>

<template>
  <div class="min-h-screen bg-black text-white font-sans pt-24 pb-12 px-4 selection:bg-emerald-500/30">
    
    <div class="max-w-6xl mx-auto">
        
        <div class="flex flex-col md:flex-row justify-between items-end mb-8 gap-6">
            <div>
                <h1 class="text-3xl font-bold tracking-tight mb-1">Portfolio</h1>
                <div class="flex items-center gap-2 text-zinc-400 text-sm">
                    <span>Welcome back, {{ currentUser?.name || '...' }}</span>
                </div>
            </div>

            <div class="flex gap-6">
                <div class="text-right">
                    <span class="block text-xs font-medium text-zinc-500 uppercase tracking-wide">Cash Balance</span>
                    <span class="text-2xl font-bold tracking-tight">{{ formatCurrency(balance.eur) }}</span>
                </div>
                <div class="text-right border-l border-zinc-800 pl-6">
                    <span class="block text-xs font-medium text-zinc-500 uppercase tracking-wide">Carbon Assets</span>
                    <span class="text-2xl font-bold tracking-tight text-emerald-400">{{ formatCO2(balance.tokens) }}</span>
                </div>
            </div>
        </div>

        <transition enter-from-class="opacity-0 translate-y-2" leave-to-class="opacity-0 translate-y-2">
            <div v-if="message.text" class="fixed bottom-6 right-6 z-50 bg-zinc-800 border border-zinc-700 text-white px-6 py-3 rounded-full shadow-2xl flex items-center gap-3 transition-all duration-300">
                <div class="h-2 w-2 rounded-full" :class="message.type === 'error' ? 'bg-rose-500' : 'bg-emerald-500'"></div>
                <span class="text-sm font-medium">{{ message.text }}</span>
            </div>
        </transition>


        <div class="grid grid-cols-1 lg:grid-cols-12 gap-6">
            
            <div class="lg:col-span-4">
                <div class="bg-zinc-900 rounded-2xl p-6 sticky top-24 border border-zinc-800/50 shadow-xl">
                    
                    <div class="bg-black rounded-lg p-1 flex mb-6">
                        <button 
                            @click="tradeMode = 'buy'"
                            class="flex-1 py-2 text-sm font-bold rounded-md transition-all duration-200"
                            :class="tradeMode === 'buy' ? 'bg-zinc-800 text-white shadow-sm' : 'text-zinc-500 hover:text-zinc-300'"
                        >
                            Buy
                        </button>
                        <button 
                            @click="tradeMode = 'sell'"
                            class="flex-1 py-2 text-sm font-bold rounded-md transition-all duration-200"
                            :class="tradeMode === 'sell' ? 'bg-zinc-800 text-white shadow-sm' : 'text-zinc-500 hover:text-zinc-300'"
                        >
                            Sell
                        </button>
                    </div>

                    <div class="space-y-4">
                        <div class="group">
                            <label class="block text-xs font-medium text-zinc-500 mb-1.5 ml-1">Quantity (g CO2)</label>
                            <div class="relative">
                                <input 
                                    type="number" 
                                    v-model.number="newOrder.amount_token" 
                                    class="w-full bg-black border border-zinc-800 rounded-xl px-4 py-3 text-lg font-medium text-white placeholder-zinc-700 focus:outline-none focus:border-emerald-500/50 focus:ring-1 focus:ring-emerald-500/50 transition-all"
                                    placeholder="0"
                                >
                                <div class="absolute right-4 top-3.5 text-zinc-600 text-sm font-medium">g</div>
                            </div>
                        </div>

                        <div class="group">
                            <label class="block text-xs font-medium text-zinc-500 mb-1.5 ml-1">Total Price (€)</label>
                            <div class="relative">
                                <input 
                                    type="number" 
                                    v-model.number="newOrder.amount_cash" 
                                    class="w-full bg-black border border-zinc-800 rounded-xl px-4 py-3 text-lg font-medium text-white placeholder-zinc-700 focus:outline-none focus:border-emerald-500/50 focus:ring-1 focus:ring-emerald-500/50 transition-all"
                                    placeholder="0.00"
                                >
                                <div class="absolute right-4 top-3.5 text-zinc-600 text-sm font-medium">EUR</div>
                            </div>
                        </div>
                    </div>

                    <button 
                        @click="createOrder" 
                        :disabled="loading || !isValidOrder"
                        class="w-full mt-8 py-4 rounded-xl font-bold text-base transition-all transform active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed shadow-lg"
                        :class="tradeMode === 'buy' 
                            ? 'bg-emerald-500 hover:bg-emerald-400 text-black shadow-emerald-500/20' 
                            : 'bg-rose-500 hover:bg-rose-400 text-white shadow-rose-500/20'"
                    >
                        <span v-if="loading" class="animate-pulse">Processing...</span>
                        <span v-else>{{ tradeMode === 'buy' ? 'Place Buy Order' : 'Place Sell Order' }}</span>
                    </button>

                </div>
            </div>


            <div class="lg:col-span-8">
                <div class="bg-zinc-900 rounded-2xl border border-zinc-800/50 shadow-xl overflow-hidden min-h-[500px] flex flex-col">
                    
                    <div class="px-6 py-4 border-b border-zinc-800 flex justify-between items-center">
                        <h2 class="font-bold text-zinc-100 flex items-center gap-2">
                            <TrendingUp class="w-4 h-4 text-emerald-500" /> Market Activity
                        </h2>
                        <button @click="fetchData" class="p-2 hover:bg-zinc-800 rounded-full text-zinc-500 hover:text-white transition-colors">
                            <RefreshCcw class="w-4 h-4" :class="{'animate-spin': loading}" />
                        </button>
                    </div>

                    <div class="grid grid-cols-12 px-6 py-3 text-xs font-medium text-zinc-500 uppercase tracking-wide border-b border-zinc-800 bg-zinc-900/50">
                        <div class="col-span-2">User</div>
                        <div class="col-span-3 text-right">Volume</div>
                        <div class="col-span-3 text-right">Price</div>
                        <div class="col-span-4 text-right">Action</div>
                    </div>

                    <div class="flex-grow overflow-y-auto">
                        
                        <div v-if="orders.length === 0" class="h-64 flex flex-col items-center justify-center text-zinc-600">
                            <div class="bg-zinc-800 p-4 rounded-full mb-3">
                                <RefreshCcw class="w-6 h-6 opacity-50" />
                            </div>
                            <span class="text-sm">Market is currently empty.</span>
                        </div>

                        <div v-for="order in orders" :key="order.order_id" 
                             class="grid grid-cols-12 px-6 py-4 items-center border-b border-zinc-800/50 hover:bg-zinc-800/40 transition-colors group">
                            
                            <div class="col-span-2 flex items-center gap-2">
                                <div class="w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold"
                                     :class="isMyOrder(order) ? 'bg-emerald-500 text-black' : 'bg-zinc-700 text-zinc-300'">
                                     {{ (isMyOrder(order) ? 'ME' : (userNames[order.user_id]?.[0] || '?')).toUpperCase() }}
                                </div>
                                <span class="text-sm font-medium truncate" :class="isMyOrder(order) ? 'text-emerald-400' : 'text-zinc-300'">
                                    {{ isMyOrder(order) ? 'You' : (userNames[order.user_id] || 'Loading...') }}
                                </span>
                            </div>

                            <div class="col-span-3 text-right font-medium text-white">
                                {{ formatCO2(order.amount_token) }}
                            </div>

                            <div class="col-span-3 text-right font-medium text-white">
                                {{ formatCurrency(order.amount_cash) }}
                            </div>

                            <div class="col-span-4 flex justify-end">
                                <button v-if="isMyOrder(order)" @click="deleteOrder(order.order_id)" 
                                        class="p-2 rounded-lg text-zinc-500 hover:text-rose-500 hover:bg-rose-500/10 transition-colors" title="Cancel Order">
                                    <X class="w-4 h-4" />
                                </button>

                                <button v-else @click="acceptOrder(order)" 
                                        class="px-5 py-1.5 rounded-lg text-xs font-bold uppercase tracking-wide transition-all transform active:scale-95 shadow-lg"
                                        :class="order.type === 'buy' 
                                            ? 'bg-rose-500 text-white hover:bg-rose-600 shadow-rose-900/20' 
                                            : 'bg-emerald-500 text-black hover:bg-emerald-400 shadow-emerald-900/20'">
                                    {{ order.type === 'buy' ? 'Sell' : 'Buy' }}
                                </button>
                            </div>

                            <div v-if="isMyOrder(order)" class="col-span-12 mt-1">
                                <span class="text-[10px] px-1.5 py-0.5 rounded bg-zinc-800 text-zinc-400 uppercase tracking-wider">
                                    Your {{ order.type }} Order
                                </span>
                            </div>

                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
  </div>
</template>

// services/shop_carbon_trains/frontend/src/App.tsx
import { useState, useEffect } from 'react'

interface Train {
  id: number;
  from: string;
  to: string;
  priceEur: number;
  priceCo2: number;
  trainNumber: string;
}

const TRAINS: Train[] = [
  { 
    id: 1, 
    from: 'Düsseldorf', 
    to: 'Paris', 
    priceEur: 79, 
    priceCo2: 17500, // ca. 500km -> 17,5kg CO2
    trainNumber: 'EST 9424' // Eurostar
  },
  { 
    id: 2, 
    from: 'Düsseldorf', 
    to: 'Vienna', 
    priceEur: 129, 
    priceCo2: 33250, // ca. 950km -> 33,25kg CO2
    trainNumber: 'ICE 21' 
  },
  { 
    id: 3, 
    from: 'Düsseldorf', 
    to: 'Copenhagen', 
    priceEur: 109, 
    priceCo2: 27300, // ca. 780km -> 27,3kg CO2
    trainNumber: 'ICE 826' 
  },
  { 
    id: 4, 
    from: 'Düsseldorf', 
    to: 'Brussels', 
    priceEur: 45, 
    priceCo2: 7000, // ca. 200km -> 7kg CO2
    trainNumber: 'EST 9412' 
  },
];

function App() {
  const [userId, setUserId] = useState(localStorage.getItem('userId') || '');
  const [booking, setBooking] = useState(false);
  const [message, setMessage] = useState('');
  const [balance, setBalance] = useState<{ moneyBalance: number, co2Balance: number } | null>(null);

  const formatNumber = (num: number) => {
    return new Intl.NumberFormat('de-DE', { minimumFractionDigits: 0, maximumFractionDigits: 2 }).format(num);
  };

  const fetchBalance = async () => {
    if (!userId) {
        setBalance(null);
        return;
    }
    try {
      const res = await fetch(`/api/wallet/balance`, {
          headers: {
              'X-User-ID': userId
          }
      });
      if (res.ok) {
        const data = await res.json();
        setBalance(data);
      } else {
          console.error('Balance request failed with status:', res.status);
          setBalance(null);
      }
    } catch (err) {
      console.error('Failed to fetch balance:', err);
      setBalance(null);
    }
  };

  useEffect(() => {
    fetchBalance();
    
    // Polling balance every 5 seconds to keep it updated
    const interval = setInterval(fetchBalance, 5000);
    return () => clearInterval(interval);
  }, [userId]);

  const bookTrain = async (train: Train) => {
    if (!userId) {
      alert('Please enter a User ID');
      return;
    }

    setBooking(true);
    setMessage('');

    try {
      const res = await fetch('/api/trains/book', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ train, userId }),
      });

      const result = await res.json();
      if (res.ok) {
        setMessage('Booking successful! Event emitted.');
        fetchBalance();
      } else {
        setMessage(`Error: ${result.error}`);
      }
    } catch (err: any) {
      setMessage(`Network error: ${err.message}`);
    } finally {
      setBooking(false);
    }
  };

  return (
    <div className="bg-gray-950 text-gray-100 min-h-screen w-full">
      <div className="max-w-6xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
        <header className="flex flex-col sm:flex-row justify-between items-center mb-12 border-b border-gray-800 pb-6 gap-6">
          <div className="text-center sm:text-left">
            <h1 className="text-4xl font-bold text-green-400">Eco Rails</h1>
            <p className="text-gray-400">Fast, Green, European.</p>
          </div>
          <div className="flex items-center gap-4">
            {balance ? (
              <div className="flex gap-3 sm:gap-4">
                <div className="bg-gray-900 border border-gray-800 px-3 py-1.5 sm:px-4 sm:py-2 rounded-lg flex flex-col items-end shadow-sm">
                  <span className="text-[10px] text-gray-500 uppercase tracking-widest">Balance</span>
                  <span className="text-sm sm:text-base font-bold text-blue-400">{formatNumber(balance.moneyBalance)} €</span>
                </div>
                <div className="bg-gray-900 border border-gray-800 px-3 py-1.5 sm:px-4 sm:py-2 rounded-lg flex flex-col items-end shadow-sm">
                  <span className="text-[10px] text-gray-500 uppercase tracking-widest">Carbon Rights</span>
                  <span className="text-sm sm:text-base font-bold text-green-400">{formatNumber(balance.co2Balance / 1000)} kg CO2</span>
                </div>
              </div>
            ) : (
               <div className="text-xs text-amber-500 bg-amber-900/20 border border-amber-500/50 px-4 py-2 rounded-md animate-pulse">
                  {userId ? 'Loading Balance...' : 'Please login via Hub'}
               </div>
            )}
          </div>
        </header>

        {message && (
          <div className={`mb-8 p-4 rounded-lg border shadow-lg animate-in fade-in slide-in-from-top-4 duration-300 ${message.includes('Error') ? 'bg-red-900/20 border-red-500/50 text-red-200' : 'bg-green-900/20 border-green-500/50 text-green-200'}`}>
            <div className="flex items-center gap-3">
                <div className={`w-2 h-2 rounded-full ${message.includes('Error') ? 'bg-red-500' : 'bg-green-500'}`}></div>
                <p className="font-medium">{message}</p>
            </div>
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-2 gap-6 lg:gap-8">
          {TRAINS.map((train) => (
            <div key={train.id} className="bg-gray-900/40 border border-gray-800 p-6 rounded-2xl hover:border-green-500/40 transition-all duration-300 group shadow-xl hover:shadow-green-900/5">
              <div className="flex justify-between items-start mb-6">
                <span className="text-[10px] font-mono text-gray-500 bg-gray-800/50 px-2 py-1 rounded tracking-wider">{train.trainNumber}</span>
                <div className="flex flex-col items-end gap-1">
                  <span className="text-lg font-bold text-blue-400">{formatNumber(train.priceEur)} €</span>
                  <span className="text-xs font-semibold text-green-400/80">{formatNumber(train.priceCo2 / 1000)} kg CO2</span>
                </div>
              </div>
              
              <div className="flex items-center gap-4 mb-8">
                <div className="flex-1">
                  <div className="text-xs text-gray-500 uppercase tracking-tighter mb-1">Departure</div>
                  <div className="text-xl font-bold text-gray-100">{train.from}</div>
                </div>
                
                <div className="flex flex-col items-center gap-1 group-hover:px-2 transition-all duration-500">
                    <div className="h-[2px] w-12 bg-gray-800 relative overflow-hidden rounded-full">
                        <div className="absolute inset-0 bg-green-500/30"></div>
                        <div className="absolute top-0 left-0 h-full w-1/2 bg-green-500 shadow-[0_0_10px_#22c55e] animate-infinite-scroll"></div>
                    </div>
                </div>

                <div className="flex-1 text-right">
                  <div className="text-xs text-gray-500 uppercase tracking-tighter mb-1">Arrival</div>
                  <div className="text-xl font-bold text-gray-100">{train.to}</div>
                </div>
              </div>

              <button 
                disabled={booking || !userId}
                onClick={() => bookTrain(train)}
                className="w-full bg-green-600 hover:bg-green-500 disabled:bg-gray-800 disabled:text-gray-500 text-white py-4 rounded-xl font-bold transition-all duration-200 shadow-lg shadow-green-900/20 active:scale-[0.98]"
              >
                {booking ? (
                    <div className="flex items-center justify-center gap-2">
                        <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                        <span>Processing...</span>
                    </div>
                ) : (!userId ? 'Login Required' : 'Book Ticket')}
              </button>
            </div>
          ))}
        </div>
      </div>
      
      <style>{`
        @keyframes infinite-scroll {
            0% { transform: translateX(-100%); }
            100% { transform: translateX(200%); }
        }
        .animate-infinite-scroll {
            animation: infinite-scroll 2s linear infinite;
        }
      `}</style>
    </div>
  )
}

export default App
